server:
  port: 8080

spring:
  cloud:
    gateway:

      default-filters:
        - name: JwtAuth

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**,/api/auth/**

        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/restaurants/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**,/api/cart/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**

        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/search/**

        # USER
        - id: user-swagger
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        
        # RESTAURANT
        - id: restaurant-swagger
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurant-service/v3/api-docs
          filters:
            - RewritePath=/restaurant-service/(?<segment>.*), /$\{segment}
        
        # ORDER
        - id: order-swagger
          uri: lb://order-service
          predicates:
            - Path=/order-service/v3/api-docs
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
        
        # PAYMENT
        - id: payment-swagger
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/v3/api-docs
          filters:
            - RewritePath=/payment-service/(?<segment>.*), /$\{segment}
        
        # ADMIN
        - id: admin-swagger
          uri: lb://admin-service
          predicates:
            - Path=/admin-service/v3/api-docs
          filters:
            - RewritePath=/admin-service/(?<segment>.*), /$\{segment}
        
        # SEARCH
        - id: search-swagger
          uri: lb://search-service
          predicates:
            - Path=/search-service/v3/api-docs
          filters:
            - RewritePath=/search-service/(?<segment>.*), /$\{segment}
app:
  jwt:
    secret: ${JWT_SECRET:EatEaseFoodDeliveryPlatformSecretKeyForJWTTokenGeneration2024}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: restaurant-service
        url: /restaurant-service/v3/api-docs
      - name: order-service
        url: /order-service/v3/api-docs
      - name: payment-service
        url: /payment-service/v3/api-docs
      - name: admin-service
        url: /admin-service/v3/api-docs
      - name: search-service
        url: /search-service/v3/api-docs
